import React from 'react';
import './home.css';

 function Home(props) {
   console.log(props.data)
  return (
    <div> 
      <p>{props.description}</p>
      <h1 className='nasat'>History of NASA</h1>
      <h2>The U.S. Congress passes legislation establishing the National Aeronautics and Space Administration (NASA), a civilian agency responsible for coordinating America’s activities in space, on July 29, 1958. NASA has since sponsored space expeditions, both human and mechanical, that have yielded vital information about the solar system and universe. It has also launched numerous earth-orbiting satellites that have been instrumental in everything from weather forecasting to navigation to global communications.

NASA was created in response to the Soviet Union’s October 4, 1957 launch of its first satellite, Sputnik I. The 183-pound, basketball-sized satellite orbited the earth in 98 minutes. The Sputnik launch caught Americans by surprise and sparked fears that the Soviets might also be capable of sending missiles with nuclear weapons from Europe to America. The United States prided itself on being at the forefront of technology, and, embarrassed, immediately began developing a response, signaling the start of the U.S.-Soviet space race.</h2>
<h2>
On November 3, 1957, the Soviets launched Sputnik II, which carried a dog named Laika. In December, America attempted to launch a satellite of its own, called Vanguard, but it exploded shortly after takeoff. On January 31, 1958, things went better with Explorer I, the first U.S. satellite to successfully orbit the earth. In July of that year, Congress passed legislation officially establishing NASA from the National Advisory Committee for Aeronautics and other government agencies, and confirming the country’s commitment to winning the space race. In May 1961, President John F. Kennedy declared that America should put a man on the moon by the end of the decade. On July 20, 1969, NASA’s Apollo 11 mission achieved that goal and made history when astronaut Neil Armstrong became the first person to set foot on the moon, famously declaring “That’s one small step for man, one giant leap for mankind."
</h2>
<h2>
NASA has continued to make great advances in space exploration since the first moonwalk, including playing a major part in the construction of the International Space Station. The agency has also suffered tragic setbacks, however, such as the disasters that killed the crews of the Challenger space shuttle in 1986 and the Columbia space shuttle in 2003. The agency has also been involved in the development of the space shuttle program, which has been used by the United States and other nations to carry satellites into space.
</h2>

<h1>Project Apollo (1960–1972) </h1>
<h2>The U.S public's perception of the Soviet lead in the Space Race (by putting the first man into space) motivated President John F. Kennedy[41] to ask the Congress on May 25, 1961, to commit the federal government to a program to land a man on the Moon by the end of the 1960s, which effectively launched the Apollo program.[42]

Apollo was one of the most expensive American scientific programs ever. It cost more than $20 billion in 1960s dollars[43] or an estimated $236 billion in present-day US dollars.[44] (In comparison, the Manhattan Project cost roughly $30.1 billion, accounting for inflation.)[44][45] It used the Saturn rockets as launch vehicles, which were far bigger than the rockets built for previous projects.[46] The spacecraft was also bigger; it had two main parts, the combined command and service module (CSM) and the Apollo Lunar Module (LM). The LM was to be left on the Moon and only the command module (CM) containing the three astronauts would return to Earth.[note 2]

The planned first crew of 3 astronauts were killed due to a fire during a 1967 preflight test for the Apollo 204 mission (later renamed Apollo 1).[47] The second crewed mission, Apollo 8, brought astronauts for the first time in a flight around the Moon in December 1968.[48] Shortly before, the Soviets had sent an uncrewed spacecraft around the Moon.[49] On the next two missions docking maneuvers that were needed for the Moon landing were practiced[50][51] and then finally the Moon landing was made on the Apollo 11 mission in July 1969.[52]

The first person to walk on the Moon was Neil Armstrong, who was followed 19 minutes later by Buzz Aldrin, while Michael Collins orbited above. Five subsequent Apollo missions also landed astronauts on the Moon, the last in December 1972. Throughout these six Apollo spaceflights, twelve men walked on the Moon. These missions returned a wealth of scientific data and 381.7 kilograms (842 lb) of lunar samples. Topics covered by experiments performed included soil mechanics, meteoroids, seismology, heat flow, lunar ranging, magnetic fields, and solar wind.[53][page needed] The Moon landing marked the end of the space race; and as a gesture, Armstrong mentioned mankind when he stepped down on the Moon.[54]

Apollo set major milestones in human spaceflight. It stands alone in sending crewed missions beyond low Earth orbit, and landing humans on another celestial body.[55] Apollo 8 was the first crewed spacecraft to orbit another celestial body, while Apollo 17 marked the last moonwalk and the last crewed mission beyond low Earth orbit. The program spurred advances in many areas of technology peripheral to rocketry and crewed spaceflight, including avionics, telecommunications, and computers. Apollo sparked interest in many fields of engineering and left many physical facilities and machines developed for the program as landmarks. Many objects and artifacts from the program are on display at various locations throughout the world, notably at the Smithsonian's Air and Space Museums.</h2>
<h1>Skylab (1965–1979) </h1>
<h2>Skylab was the United States' first and only independently built space station.[56] Conceived in 1965 as a workshop to be constructed in space from a spent Saturn IB upper stage, the 169,950 lb (77,088 kg) station was constructed on Earth and launched on May 14, 1973, atop the first two stages of a Saturn V, into a 235-nautical-mile (435 km) orbit inclined at 50° to the equator. Damaged during launch by the loss of its thermal protection and one electricity-generating solar panel, it was repaired to functionality by its first crew. It was occupied for a total of 171 days by 3 successive crews in 1973 and 1974.[56] It included a laboratory for studying the effects of microgravity, and a solar observatory.[56] NASA planned to have a Space Shuttle dock with it, and elevate Skylab to a higher safe altitude, but the Shuttle was not ready for flight before Skylab's re-entry on July 11, 1979.[57]

To reduce cost, NASA used one of the Saturn V rockets originally earmarked for a canceled Apollo mission to launch the Skylab. Apollo spacecraft were used for transporting astronauts to and from the station. Three three-man crews stayed aboard the station for periods of 28, 59, and 84 days. Skylab's habitable volume was 11,290 cubic feet (320 m3), which was 30.7 times bigger than that of the Apollo Command Module.[57]</h2>
<h1>International Space Station (1993–present) </h1>
<h2>The International Space Station (ISS) combines NASA's Space Station Freedom project with the Soviet/Russian Mir-2 station, the European Columbus station, and the Japanese Kibō laboratory module.[69] NASA originally planned in the 1980s to develop Freedom alone, but US budget constraints led to the merger of these projects into a single multi-national program in 1993, managed by NASA, the Russian Federal Space Agency (RKA), the Japan Aerospace Exploration Agency (JAXA), the European Space Agency (ESA), and the Canadian Space Agency (CSA).[70][71] The station consists of pressurized modules, external trusses, solar arrays and other components, which were manufactured in various factories around the world, and have been launched by Russian Proton and Soyuz rockets, and the US Space Shuttles.[69] The on-orbit assembly began in 1998, the completion of the US Orbital Segment occurred in 2009 and the completion of the Russian Orbital Segment occurred in 2010, though there are some debates of whether new modules should be added in the segment. The ownership and use of the space station is established in intergovernmental treaties and agreements[72] which divide the station into two areas and allow Russia to retain full ownership of the Russian Orbital Segment (with the exception of Zarya),[73][74] with the US Orbital Segment allocated between the other international partners.[72]

Long-duration missions to the ISS are referred to as ISS Expeditions. Expedition crew members typically spend approximately six months on the ISS.[75] The initial expedition crew size was three, temporarily decreased to two following the Columbia disaster. Since May 2009, expedition crew size has been six crew members.[76] Crew size is expected to be increased to seven, the number the ISS was designed for, once the Commercial Crew Program becomes operational.[77] The ISS has been continuously occupied for the past 21 years and 216 days, having exceeded the previous record held by Mir; and has been visited by astronauts and cosmonauts from 15 different nations.[78][79]

The station can be seen from the Earth with the naked eye and, as of 2022, is the largest artificial satellite in Earth orbit with a mass and volume greater than that of any previous space station.[80] The Soyuz spacecraft delivers crew members, stays docked for their half-year-long missions and then returns them home. Several uncrewed cargo spacecraft provide service to the ISS; they are the Russian Progress spacecraft which has done so since 2000, the European Automated Transfer Vehicle (ATV) since 2008, the Japanese H-II Transfer Vehicle (HTV) since 2009, the SpaceX Dragon from 2012 until 2020, and the American Cygnus spacecraft since 2013. The Space Shuttle, before its retirement, was also used for cargo transfer and would often switch out expedition crew members, although it did not have the capability to remain docked for the duration of their stay. Until another US crewed spacecraft is ready, crew members will travel to and from the International Space Station exclusively aboard the Soyuz.[81] The highest number of people occupying the ISS has been thirteen; this occurred three times during the late Shuttle ISS assembly missions.[82]

On March 29, 2019, the ISS was scheduled to have its first all-female spacewalk, but it was delayed; Jessica Meir and Christina Koch performed the first all-female spacewalk on October 18, as part of a lengthy series of upgrades to the ISS' power systems and physics observatories.[83][84][85] The ISS program is expected to continue to 2030.[86]</h2>
<h1>Constellation program (2005–2010) </h1>
<h2>While the Space Shuttle program was still suspended after the loss of Columbia, President George W. Bush announced the Vision for Space Exploration including the retirement of the Space Shuttle after completing the International Space Station. The plan was enacted into law by the NASA Authorization Act of 2005 and directs NASA to develop and launch the Crew Exploration Vehicle (later called Orion) by 2010, return Americans to the Moon by 2020, land on Mars as feasible, repair the Hubble Space Telescope, and continue scientific investigation through robotic solar system exploration, human presence on the ISS, Earth observation, and astrophysics research. The crewed exploration goals prompted NASA's Constellation program.[87]

On December 4, 2006, NASA announced it was planning a permanent Moon base.[88] The goal was to start building the Moon base by 2020, and by 2024, have a fully functional base that would allow for crew rotations and in-situ resource utilization. However, in 2009, the Augustine Committee found the program to be on an "unsustainable trajectory."[89] In February 2010, President Barack Obama's administration proposed eliminating public funds for it.[90]</h2>
<h1>Commercial Crew Program (2011–present) </h1>
<h2>The Commercial Crew Program (CCP) provides commercially-operated crew transportation service to and from the International Space Station (ISS) under contract to NASA, conducting crew rotations between the expeditions of the International Space Station program. American space manufacturer SpaceX began providing service in 2020, using the Crew Dragon spacecraft, and NASA plans to add Boeing when its Boeing Starliner spacecraft becomes operational some time after 2022.

The spacecraft are owned and operated by the vendor, and crew transportation is provided to NASA as a commercial service. Each mission sends up to four astronauts to the ISS, with an option for a fifth passenger available. Operational flights occur approximately once every six months for missions that last for approximately six months. A spacecraft remains docked to the ISS during its mission, and missions usually overlap by at least a few days. Between the retirement of the Space Shuttle in 2011 and the first operational CCP mission in 2020, NASA relied on the Soyuz program to transport its astronauts to the ISS.

A Crew Dragon spacecraft is launched to space atop a Falcon 9 Block 5 launch vehicle and the capsule returns to Earth via splashdown in the ocean near Florida. The program's first operational mission, SpaceX Crew-1, launched on 16 November 2020. Boeing Starliner spacecraft will participate after its final test flight, launched atop an Atlas V N22 or Vulcan Centaur launch vehicle. Instead of a splashdown, a Starliner capsule will return on land with airbags at one of four designated sites in the western United States.

Development of the Commercial Crew Program began in 2011 as NASA shifted from internal development of crewed vehicles to perform ISS crew rotation to commercial industry development of transport to the ISS. A series of open competitions over the following two years saw successful bids from Boeing, Blue Origin, Sierra Nevada, and SpaceX to develop proposals for ISS crew transport vehicles. In 2014, NASA awarded separate fixed-price contracts to Boeing and SpaceX to develop their respective systems and to fly astronauts to the ISS. Each contract required four successful demonstrations to achieve human rating for the system: pad abort, uncrewed orbital test, launch abort, and crewed orbital test. Operational missions were initially planned to begin in 2017, but delays required NASA to purchase additional seats on Soyuz spacecraft up to Soyuz MS-17.</h2>
<h1>Journey to Mars (2010–2017)</h1>
<h2>President Obama's plan was to develop American private spaceflight capabilities to get astronauts to the International Space Station, replace Russian Soyuz capsules, and use Orion capsules for ISS emergency escape purposes. During a speech at the Kennedy Space Center on April 15, 2010, Obama proposed a new heavy-lift vehicle (HLV) to replace the formerly planned Ares V.[91] In his speech, Obama called for a crewed mission to an asteroid as soon as 2025, and a crewed mission to Mars orbit by the mid-2030s.[91] The NASA Authorization Act of 2010 was passed by Congress and signed into law on October 11, 2010.[92] The act officially canceled the Constellation program.[92]

The NASA Authorization Act of 2010 required a newly designed HLV be chosen within 90 days of its passing; the launch vehicle was given the name Space Launch System. The new law also required the construction of a beyond low earth orbit spacecraft.[93] The Orion spacecraft, which was being developed as part of the Constellation program, was chosen to fulfill this role.[94] The Space Launch System is planned to launch both Orion and other necessary hardware for missions beyond low Earth orbit.[95] The SLS is to be upgraded over time with more powerful versions. The initial capability of SLS is required to be able to lift 70 t (150,000 lb) (later 95 t or 209,000 lb) into LEO. It is then planned to be upgraded to 105 t (231,000 lb) and then eventually to 130 t (290,000 lb).[94][96] The Orion capsule first flew on Exploration Flight Test 1 (EFT-1), an uncrewed test flight that was launched on December 5, 2014, atop a Delta IV Heavy rocket.[96]

NASA undertook a feasibility study in 2012 and developed the Asteroid Redirect Mission as an uncrewed mission to move a boulder-sized near-Earth asteroid (or boulder-sized chunk of a larger asteroid) into lunar orbit. The mission would demonstrate ion thruster technology, and develop techniques that could be used for planetary defense against an asteroid collision, as well as a cargo transport to Mars in support of a future human mission. The Moon-orbiting boulder might then later be visited by astronauts. The Asteroid Redirect Mission was cancelled in 2017 as part of the FY2018 NASA budget, the first one under President Donald Trump.[97]

The Orion spacecraft conducted an uncrewed test launch on a Delta IV Heavy rocket in December 2014.[98]</h2>
<h1>Artemis program (2017–present)</h1>
<h2>Since 2017, NASA's crewed spaceflight program has been the Artemis program, which involves the help of U.S. commercial spaceflight companies and international partners such as ESA, JAXA, and CSA.[99] The goal of this program is to land "the first woman and the next man" on the lunar south pole region by 2024. Artemis would be the first step towards the long-term goal of establishing a sustainable presence on the Moon, laying the foundation for companies to build a lunar economy, and eventually sending humans to Mars.

The Orion Crew Exploration Vehicle was held over from the canceled Constellation program for Artemis. Artemis 1 is the uncrewed initial launch of Space Launch System (SLS) that would also send an Orion spacecraft on a Distant Retrograde Orbit.[100]

NASA's next major space initiative is to be the construction of the Lunar Gateway. This initiative is to involve the construction of a new space station, which will have many features in common with the current International Space Station, except that it will be in orbit about the Moon, instead of the Earth.[101] This space station will be designed primarily for non-continuous human habitation. The first tentative steps of returning to crewed lunar missions will be Artemis 2, which is to include the Orion crew module, propelled by the SLS, and is to launch in 2024.[99] This mission is to be a 10-day mission planned to briefly place a crew of four into a Lunar flyby.[96] The construction of the Gateway would begin with the proposed Artemis 3, which is planned to deliver a crew of four to Lunar orbit along with the first modules of the Gateway. This mission would last for up to 30 days. NASA plans to build full scale deep space habitats such as the Lunar Gateway and the Nautilus-X as part of its Next Space Technologies for Exploration Partnerships (NextSTEP) program.[102] In 2017, NASA was directed by the congressional NASA Transition Authorization Act of 2017 to get humans to Mars-orbit (or to the Martian surface) by the 2030s.[103][104]

In support of the Artemis missions, NASA has been funding private companies to land robotic probes on the lunar surface in a program known as the Commercial Lunar Payload Services. As of March 2022, NASA has awarded contracts to four companies for robotic lunar probes including Intuitive Machines, Masten Space Systems, Firefly Space Systems, and Astrobotic.[105]

In September 2020, as a part of the Artemis program, NASA outlined a plan to send astronauts to the Moon by 2024. The astronauts are to travel in the Orion capsule, launched on the SLS rocket.[106]

On April 16, 2021, NASA announced they had selected the SpaceX Lunar Starship as its Human Landing System. The agency's Space Launch System rocket will launch four astronauts aboard the Orion spacecraft for their multi-day journey to lunar orbit where they will transfer to SpaceX's Starship for the final leg of their journey to the surface of the Moon.[107]

In November 2021, it was announced that the goal of landing astronauts on the Moon by 2024 had slipped to no earlier than 2025 due to numerous factors. As of January 2022, NASA plans to launch Artemis 1 in May 2022, Artemis 2 in May 2024 and Artemis 3 sometime in 2025.[108][109] Additional Artemis missions, Artemis 4 and Artemis 5, are planned to launch after 2025.[110]</h2>
<h1>Built by NASA</h1>
<h2>Goddard Space Flight Center (GSFC), located in Greenbelt, Maryland, was commissioned by NASA on March 1, 1959. It is the largest combined organization of scientists and engineers in the United States dedicated to increasing knowledge of the Earth, the Solar System, and the Universe via observations from space. GSFC is a major U.S. laboratory for developing and operating unmanned scientific spacecraft. GSFC also operates two spaceflight tracking and data acquisition networks (the Space Network and the Near Earth Network), develops and maintains advanced space and Earth science data information systems, and develops satellite systems for the National Oceanic and Atmospheric Administration (NOAA). External facilities of the GSFC include the Wallops Flight Facility, the Goddard Institute for Space Studies at Columbia University, and the Katherine Johnson Independent Verification and Validation Facility.

John C. Stennis Space Center, originally the "Mississippi Test Facility", is located in Hancock County, Mississippi, on the banks of the Pearl River at the Mississippi–Louisiana border. Commissioned on October 25, 1961, it was NASA's largest rocket engine test facility until the end of the Space Shuttle program. It is currently used for rocket testing by over 30 local, state, national, international, private, and public companies and agencies. It contains the NASA Shared Services Center.[130]

Manned Spacecraft Center (MSC) is the NASA center for human spaceflight training, research and flight control. Created on November 1, 1961, the facility consists of a complex of 100 buildings constructed in 1962–1963 on 1,620 acres (656 ha) of land donated by Rice University in Houston, Texas.[131] The center grew out of the Space Task Group formed soon after the creation of NASA to co-ordinate the US human spaceflight program. It is home to the United States Astronaut Corps and is responsible for training astronauts from the U.S. and its international partners, and includes the Christopher C. Kraft Jr. Mission Control Center.[131] The center was renamed in honor of the late U.S. president and Texas native Lyndon B. Johnson on February 19, 1973.[132][133]

John F. Kennedy Space Center (KSC), located west of Cape Canaveral Space Force Station in Florida, is one of the best known NASA facilities. Named the "Launch Operations Center" at its creation on July 1, 1962, it was renamed in honor of the late U.S. president on November 29, 1963,[134][135] and has been the launch site for every United States human space flight since 1968. KSC continues to manage and operate unmanned rocket launch facilities for America's civilian space program from three pads at Cape Canaveral. Its Vehicle Assembly Building (VAB) is the fourth-largest structure in the world by volume[136] and was the largest when completed in 1965.[137] A total of 13,100 people worked at the center as of 2011. Approximately 2,100 are employees of the federal government; the rest are contractors.[138]

Subordinate facilities include the Wallops Flight Facility in Wallops Island, Virginia; the Michoud Assembly Facility in New Orleans, Louisiana; the White Sands Test Facility in Las Cruces, New Mexico; and Deep Space Network stations in Barstow, California; Madrid, Spain; and Canberra, Australia.</h2>
<h1>Budget</h1>
<h2>NASA's share of the total federal budget peaked at approximately 4.41% in 1966 during the Apollo program, then rapidly declined to approximately 1% in 1975, and stayed around that level through 1998.[203][207] The percentage then gradually dropped, until leveling off again at around half a percent in 2006 (estimated in 2012 at 0.48% of the federal budget).[208] In a March 2012 hearing of the United States Senate Science Committee, science communicator Neil deGrasse Tyson testified that "Right now, NASA's annual budget is half a penny on your tax dollar. For twice that—a penny on a dollar—we can transform the country from a sullen, dispirited nation, weary of economic struggle, to one where it has reclaimed its 20th century birthright to dream of tomorrow."[209][210]

Despite this, public perception of NASA's budget differs significantly: a 1997 poll indicated that most Americans believed that 20% of the federal budget went to NASA.[211]

For Fiscal Year 2015, NASA received an appropriation of US$18.01 billion from Congress—$549 million more than requested and approximately $350 million more than the 2014 NASA budget passed by Congress.[212]

In Fiscal Year 2016, NASA received $19.3 billion.[213]

President Donald Trump signed the NASA Transition Authorization Act of 2017 in March, which set the 2017 budget at around $19.5 billion.[213] The budget is also reported as $19.3 billion for 2017, with $20.7 billion proposed for FY2018.[214][215]

Examples of some proposed FY2018 budgets:[215]

<li>Exploration: $4.79 billion</li>
<li>Planetary science: $2.23 billion</li>
<li>Earth science: $1.92 billion</li>
<li>Aeronautics: $0.685 billion</li>
</h2>
    </div>
  
  )
}

export default Home;